<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="CelesteMod.props" />

	<PropertyGroup>
		<CelesteRootPath>C:/Program Files (x86)/Steam/steamapps/common/Celeste</CelesteRootPath>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Celeste.Mod.$(AssemblyName)</RootNamespace>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>true</ImplicitUsings>
		<UseCelestePublicizer>false</UseCelestePublicizer>
	</PropertyGroup>

	<ItemGroup>
		<CelesteModReference Include="MaxHelpingHand" />
		<CelesteModReference Include="PandorasBox" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Krafs.Publicizer" Version="2.3.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Publicize Include="Celeste" />
		<Publicize Include="PandorasBox.PandorasBox" />
	</ItemGroup>
	
	<ItemGroup>
		<Reference Include="NLua.dll">
			<HintPath>$(CelesteRootPath)/NLua.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Import Project="CelesteMod.targets" />
</Project>